Revert "resolved ERROR:app.services.registration_service:Registration confirmation error: 'dict' object has no attribute 'lower'"
This reverts commit 8124481fd8907901e2fcdf7a2249b94f41826d9f.