Message refactor (#217)
* message refactoring

* session issue - Duplicate entry issue

* Squashed commit of the following:

commit 7319a58a5b281b5f97abb2bc3678756974757448
Author: shubham-mohap <shubham@mohap.ai>
Date:   Thu Oct 9 16:16:28 2025 +0530

    message refactoring (#213)

commit b161d724e1626fc00c177dc7b1dee069de340838
Merge: ced2593 1e4e048
Author: priyasoni9 <priya.soni@mohap.ai>
Date:   Thu Oct 9 13:53:06 2025 +0530

    Merge pull request #210 from mohap-ai/dev_message

    Dev message

commit 1e4e048b705e1f36b29a895e6eb36ce307f69054
Merge: 30dcf59 ced2593
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Thu Oct 9 13:52:45 2025 +0530

    Merge branch 'main_release' into dev_message

commit 30dcf599c6ea13db2ccb53c93ee6cc6de9817481
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Thu Oct 9 13:48:02 2025 +0530

    iso error resolved

    INFO:app.services.exit_service:Authentication token cleared: False
    ERROR:app.services.exit_service:Error clearing session data: 'str' object has no attribute 'isoformat'
    INFO:app.services.exit_service:Session data cleared: False

commit ced2593b4f73d830900f3fa13eb8fd12dc13593a
Author: priyasoni9 <priya.soni@mohap.ai>
Date:   Thu Oct 9 13:41:47 2025 +0530

    Dev message (#209)

    * added rfq initial message

    * intent based message and routing

    * testing buttons

    * ADDED EXIT button

    * ADDED Contact support as button and exit as footer

    * added enhanced labels

    * fixes some error

    ERROR:app.services.chat_service:Error checking auth flow response: 'dict' object has no attribute 'lower'
    ERROR:app.services.chat_service:Error tracking meaningful message: slice(None, 50, None)
    ERROR:app.services.user_cache_service:Error storing meaningful message for 918824242260: slice(None, 50, None)
    ERROR:app.services.chat_service:Error in processing_message: slice(None, 50, None)

    * updated prompt and added logs

    * exit message chnages

    ---------

    Co-authored-by: priyasoni24 <priya.soni@bluecrestsoft.com>

commit b3ba1a213045f885df0de4dada87cd8d93174311
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Thu Oct 9 13:20:55 2025 +0530

    exit message chnages

commit 236ed454f6ccc151bc972eed2256232a4f826456
Merge: c89c21d 1db8ef1
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Thu Oct 9 10:45:44 2025 +0530

    Merge branch 'main_release' into dev_message

commit c89c21d0c67348c995a4b2bd8441219e6b58e451
Merge: 69da52d 2d091cb
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Thu Oct 9 09:40:50 2025 +0530

    Merge branch 'main_release' into dev_message

commit 69da52de75e785cb6bf94e3e36f650dcdadeadae
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Thu Oct 9 09:39:40 2025 +0530

    updated prompt and added logs

commit d5d7641dade477f780930db541152b45d810cba0
Merge: 02fc84f 955880f
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Thu Oct 9 09:38:09 2025 +0530

    Merge branch 'main_release' into dev_message

commit 02fc84fbc8b4b4bf91b13fa219ed5ca60f2dee5d
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Wed Oct 8 18:21:54 2025 +0530

    fixes some error

    ERROR:app.services.chat_service:Error checking auth flow response: 'dict' object has no attribute 'lower'
    ERROR:app.services.chat_service:Error tracking meaningful message: slice(None, 50, None)
    ERROR:app.services.user_cache_service:Error storing meaningful message for 918824242260: slice(None, 50, None)
    ERROR:app.services.chat_service:Error in processing_message: slice(None, 50, None)

commit b98b4d8b1ef3e68fb1105b5853a472a6e55ad955
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Wed Oct 8 18:11:33 2025 +0530

    added enhanced labels

commit 75485baa8064d3970c23468c1a892a1002833451
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Wed Oct 8 17:47:03 2025 +0530

    ADDED Contact support as button and exit as footer

commit c8aaf11d5eab906d741768afbcbd749290cfd659
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Wed Oct 8 17:09:27 2025 +0530

    ADDED EXIT button

commit fe9a80459e0ced83fc438a0f9b0e819b4caed364
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Wed Oct 8 16:57:57 2025 +0530

    testing buttons

commit 4e747f6a31563854ea59f6ffc66a5c86a7b1a551
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Wed Oct 8 16:01:47 2025 +0530

    intent based message and routing

commit d6eab43ef7d8b8e67e71cfda478ac30be270c405
Author: priyasoni24 <priya.soni@bluecrestsoft.com>
Date:   Wed Oct 8 15:38:33 2025 +0530

    added rfq initial message